/* World Cup 2026 Map — generated from updated uploaded DB/CSV dataset. */
window.WC_DATA = {
  "meta": {
    "title": "World Cup 2026 Map",
    "defaultTheme": "dark",
    "version": "realmap-v10-3-updated-data-production-fix",
    "source": "Updated uploaded World Cup 2026 DB/CSV dataset with API-Football live overlay",
    "liveRefreshMs": 1200000
  },
  "stadiums": [
    {
      "cityId": 1,
      "id": "atlanta",
      "city": "Atlanta",
      "country": "United States",
      "countryCode": "USA",
      "countryFlag": "🇺🇸",
      "venue": "Mercedes-Benz Stadium",
      "name": "Mercedes-Benz Stadium",
      "region": "East",
      "airportCode": "ATL",
      "lat": 33.7554,
      "lng": -84.4009,
      "capacity": 75000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 8,
      "matchNumbers": [
        13,
        25,
        37,
        52,
        70,
        80,
        95,
        102
      ],
      "nextMatchNumber": 13
    },
    {
      "cityId": 2,
      "id": "boston",
      "city": "Boston",
      "country": "United States",
      "countryCode": "USA",
      "countryFlag": "🇺🇸",
      "venue": "Gillette Stadium",
      "name": "Gillette Stadium",
      "region": "East",
      "airportCode": "BOS",
      "lat": 42.0909,
      "lng": -71.2643,
      "capacity": 65000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 7,
      "matchNumbers": [
        7,
        18,
        30,
        46,
        61,
        75,
        97
      ],
      "nextMatchNumber": 7
    },
    {
      "cityId": 3,
      "id": "dallas",
      "city": "Dallas",
      "country": "United States",
      "countryCode": "USA",
      "countryFlag": "🇺🇸",
      "venue": "AT&T Stadium",
      "name": "AT&T Stadium",
      "region": "Central",
      "airportCode": "DAL",
      "lat": 32.7473,
      "lng": -97.0945,
      "capacity": 94000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 9,
      "matchNumbers": [
        10,
        22,
        41,
        57,
        72,
        77,
        86,
        93,
        101
      ],
      "nextMatchNumber": 10
    },
    {
      "cityId": 4,
      "id": "houston",
      "city": "Houston",
      "country": "United States",
      "countryCode": "USA",
      "countryFlag": "🇺🇸",
      "venue": "NRG Stadium",
      "name": "NRG Stadium",
      "region": "Central",
      "airportCode": "IAH",
      "lat": 29.6847,
      "lng": -95.4107,
      "capacity": 72000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 7,
      "matchNumbers": [
        9,
        21,
        33,
        45,
        63,
        74,
        89
      ],
      "nextMatchNumber": 9
    },
    {
      "cityId": 5,
      "id": "kansas-city",
      "city": "Kansas City",
      "country": "United States",
      "countryCode": "USA",
      "countryFlag": "🇺🇸",
      "venue": "Arrowhead Stadium",
      "name": "Arrowhead Stadium",
      "region": "Central",
      "airportCode": "MCI",
      "lat": 39.0489,
      "lng": -94.4839,
      "capacity": 73000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 6,
      "matchNumbers": [
        19,
        35,
        58,
        71,
        88,
        100
      ],
      "nextMatchNumber": 19
    },
    {
      "cityId": 6,
      "id": "los-angeles",
      "city": "Los Angeles",
      "country": "United States",
      "countryCode": "USA",
      "countryFlag": "🇺🇸",
      "venue": "SoFi Stadium",
      "name": "SoFi Stadium",
      "region": "West",
      "airportCode": "LAX",
      "lat": 33.9535,
      "lng": -118.3392,
      "capacity": 70000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 8,
      "matchNumbers": [
        4,
        16,
        26,
        38,
        59,
        73,
        83,
        98
      ],
      "nextMatchNumber": 4
    },
    {
      "cityId": 7,
      "id": "miami",
      "city": "Miami",
      "country": "United States",
      "countryCode": "USA",
      "countryFlag": "🇺🇸",
      "venue": "Hard Rock Stadium",
      "name": "Hard Rock Stadium",
      "region": "East",
      "airportCode": "MIA",
      "lat": 25.958,
      "lng": -80.2389,
      "capacity": 65000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 7,
      "matchNumbers": [
        15,
        39,
        51,
        69,
        87,
        99,
        103
      ],
      "nextMatchNumber": 15
    },
    {
      "cityId": 8,
      "id": "new-york-new-jersey",
      "city": "New York/New Jersey",
      "country": "United States",
      "countryCode": "USA",
      "countryFlag": "🇺🇸",
      "venue": "MetLife Stadium",
      "name": "MetLife Stadium",
      "region": "East",
      "airportCode": "EWR",
      "lat": 40.8135,
      "lng": -74.0745,
      "capacity": 82500,
      "status": "upcoming",
      "image": "",
      "totalMatches": 8,
      "matchNumbers": [
        6,
        17,
        43,
        56,
        67,
        78,
        91,
        104
      ],
      "nextMatchNumber": 6
    },
    {
      "cityId": 9,
      "id": "philadelphia",
      "city": "Philadelphia",
      "country": "United States",
      "countryCode": "USA",
      "countryFlag": "🇺🇸",
      "venue": "Lincoln Financial Field",
      "name": "Lincoln Financial Field",
      "region": "East",
      "airportCode": "PHL",
      "lat": 39.9008,
      "lng": -75.1675,
      "capacity": 69000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 6,
      "matchNumbers": [
        11,
        31,
        42,
        55,
        68,
        90
      ],
      "nextMatchNumber": 11
    },
    {
      "cityId": 10,
      "id": "san-francisco-bay-area",
      "city": "San Francisco Bay Area",
      "country": "United States",
      "countryCode": "USA",
      "countryFlag": "🇺🇸",
      "venue": "Levi's Stadium",
      "name": "Levi's Stadium",
      "region": "West",
      "airportCode": "SFO",
      "lat": 37.403,
      "lng": -121.97,
      "capacity": 71000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 6,
      "matchNumbers": [
        5,
        20,
        32,
        44,
        60,
        82
      ],
      "nextMatchNumber": 5
    },
    {
      "cityId": 11,
      "id": "seattle",
      "city": "Seattle",
      "country": "United States",
      "countryCode": "USA",
      "countryFlag": "🇺🇸",
      "venue": "Lumen Field",
      "name": "Lumen Field",
      "region": "West",
      "airportCode": "SEA",
      "lat": 47.5952,
      "lng": -122.3316,
      "capacity": 69000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 6,
      "matchNumbers": [
        14,
        29,
        50,
        65,
        81,
        94
      ],
      "nextMatchNumber": 14
    },
    {
      "cityId": 12,
      "id": "toronto",
      "city": "Toronto",
      "country": "Canada",
      "countryCode": "CAN",
      "countryFlag": "🇨🇦",
      "venue": "BMO Field",
      "name": "BMO Field",
      "region": "East",
      "airportCode": "YYZ",
      "lat": 43.6332,
      "lng": -79.4186,
      "capacity": 45000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 6,
      "matchNumbers": [
        3,
        23,
        34,
        47,
        62,
        84
      ],
      "nextMatchNumber": 3
    },
    {
      "cityId": 13,
      "id": "vancouver",
      "city": "Vancouver",
      "country": "Canada",
      "countryCode": "CAN",
      "countryFlag": "🇨🇦",
      "venue": "BC Place",
      "name": "BC Place",
      "region": "West",
      "airportCode": "YVR",
      "lat": 49.2767,
      "lng": -123.1119,
      "capacity": 54000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 7,
      "matchNumbers": [
        8,
        27,
        40,
        49,
        66,
        85,
        96
      ],
      "nextMatchNumber": 8
    },
    {
      "cityId": 14,
      "id": "guadalajara",
      "city": "Guadalajara",
      "country": "Mexico",
      "countryCode": "MEX",
      "countryFlag": "🇲🇽",
      "venue": "Estadio Akron",
      "name": "Estadio Akron",
      "region": "Central",
      "airportCode": "GDL",
      "lat": 20.6819,
      "lng": -103.4622,
      "capacity": 48000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 4,
      "matchNumbers": [
        2,
        28,
        48,
        64
      ],
      "nextMatchNumber": 2
    },
    {
      "cityId": 15,
      "id": "mexico-city",
      "city": "Mexico City",
      "country": "Mexico",
      "countryCode": "MEX",
      "countryFlag": "🇲🇽",
      "venue": "Estadio Azteca",
      "name": "Estadio Azteca",
      "region": "Central",
      "airportCode": "MEX",
      "lat": 19.3029,
      "lng": -99.1505,
      "capacity": 83000,
      "status": "upcoming",
      "image": "",
      "totalMatches": 5,
      "matchNumbers": [
        1,
        24,
        53,
        79,
        92
      ],
      "nextMatchNumber": 1
    },
    {
      "cityId": 16,
      "id": "monterrey",
      "city": "Monterrey",
      "country": "Mexico",
      "countryCode": "MEX",
      "countryFlag": "🇲🇽",
      "venue": "Estadio BBVA",
      "name": "Estadio BBVA",
      "region": "Central",
      "airportCode": "MTY",
      "lat": 25.6685,
      "lng": -100.2445,
      "capacity": 53500,
      "status": "upcoming",
      "image": "",
      "totalMatches": 4,
      "matchNumbers": [
        12,
        36,
        54,
        76
      ],
      "nextMatchNumber": 12
    }
  ],
  "teams": {
    "1": {
      "id": 1,
      "name": "Mexico",
      "code": "MEX",
      "group": "A",
      "flag": "🇲🇽",
      "isPlaceholder": false
    },
    "2": {
      "id": 2,
      "name": "South Africa",
      "code": "RSA",
      "group": "A",
      "flag": "🇿🇦",
      "isPlaceholder": false
    },
    "3": {
      "id": 3,
      "name": "South Korea",
      "code": "KOR",
      "group": "A",
      "flag": "🇰🇷",
      "isPlaceholder": false
    },
    "4": {
      "id": 4,
      "name": "Czechia",
      "code": "CZE",
      "group": "A",
      "flag": "🇨🇿",
      "isPlaceholder": false
    },
    "5": {
      "id": 5,
      "name": "Canada",
      "code": "CAN",
      "group": "B",
      "flag": "🇨🇦",
      "isPlaceholder": false
    },
    "6": {
      "id": 6,
      "name": "Bosnia and Herzegovina",
      "code": "BIH",
      "group": "B",
      "flag": "🇧🇦",
      "isPlaceholder": false
    },
    "7": {
      "id": 7,
      "name": "Qatar",
      "code": "QAT",
      "group": "B",
      "flag": "🇶🇦",
      "isPlaceholder": false
    },
    "8": {
      "id": 8,
      "name": "Switzerland",
      "code": "SUI",
      "group": "B",
      "flag": "🇨🇭",
      "isPlaceholder": false
    },
    "9": {
      "id": 9,
      "name": "Brazil",
      "code": "BRA",
      "group": "C",
      "flag": "🇧🇷",
      "isPlaceholder": false
    },
    "10": {
      "id": 10,
      "name": "Morocco",
      "code": "MAR",
      "group": "C",
      "flag": "🇲🇦",
      "isPlaceholder": false
    },
    "11": {
      "id": 11,
      "name": "Haiti",
      "code": "HAI",
      "group": "C",
      "flag": "🇭🇹",
      "isPlaceholder": false
    },
    "12": {
      "id": 12,
      "name": "Scotland",
      "code": "SCO",
      "group": "C",
      "flag": "🏴",
      "isPlaceholder": false
    },
    "13": {
      "id": 13,
      "name": "USA",
      "code": "USA",
      "group": "D",
      "flag": "🇺🇸",
      "isPlaceholder": false
    },
    "14": {
      "id": 14,
      "name": "Paraguay",
      "code": "PAR",
      "group": "D",
      "flag": "🇵🇾",
      "isPlaceholder": false
    },
    "15": {
      "id": 15,
      "name": "Australia",
      "code": "AUS",
      "group": "D",
      "flag": "🇦🇺",
      "isPlaceholder": false
    },
    "16": {
      "id": 16,
      "name": "Türkiye",
      "code": "TUR",
      "group": "D",
      "flag": "🇹🇷",
      "isPlaceholder": false
    },
    "17": {
      "id": 17,
      "name": "Germany",
      "code": "GER",
      "group": "E",
      "flag": "🇩🇪",
      "isPlaceholder": false
    },
    "18": {
      "id": 18,
      "name": "Curaçao",
      "code": "CUR",
      "group": "E",
      "flag": "🇨🇼",
      "isPlaceholder": false
    },
    "19": {
      "id": 19,
      "name": "Côte d'Ivoire",
      "code": "CIV",
      "group": "E",
      "flag": "🇨🇮",
      "isPlaceholder": false
    },
    "20": {
      "id": 20,
      "name": "Ecuador",
      "code": "ECU",
      "group": "E",
      "flag": "🇪🇨",
      "isPlaceholder": false
    },
    "21": {
      "id": 21,
      "name": "Netherlands",
      "code": "NED",
      "group": "F",
      "flag": "🇳🇱",
      "isPlaceholder": false
    },
    "22": {
      "id": 22,
      "name": "Japan",
      "code": "JPN",
      "group": "F",
      "flag": "🇯🇵",
      "isPlaceholder": false
    },
    "23": {
      "id": 23,
      "name": "Sweden",
      "code": "SWE",
      "group": "F",
      "flag": "🇸🇪",
      "isPlaceholder": false
    },
    "24": {
      "id": 24,
      "name": "Tunisia",
      "code": "TUN",
      "group": "F",
      "flag": "🇹🇳",
      "isPlaceholder": false
    },
    "25": {
      "id": 25,
      "name": "Belgium",
      "code": "BEL",
      "group": "G",
      "flag": "🇧🇪",
      "isPlaceholder": false
    },
    "26": {
      "id": 26,
      "name": "Egypt",
      "code": "EGY",
      "group": "G",
      "flag": "🇪🇬",
      "isPlaceholder": false
    },
    "27": {
      "id": 27,
      "name": "IR Iran",
      "code": "IRN",
      "group": "G",
      "flag": "🇮🇷",
      "isPlaceholder": false
    },
    "28": {
      "id": 28,
      "name": "New Zealand",
      "code": "NZL",
      "group": "G",
      "flag": "🇳🇿",
      "isPlaceholder": false
    },
    "29": {
      "id": 29,
      "name": "Spain",
      "code": "ESP",
      "group": "H",
      "flag": "🇪🇸",
      "isPlaceholder": false
    },
    "30": {
      "id": 30,
      "name": "Cabo Verde",
      "code": "CPV",
      "group": "H",
      "flag": "🇨🇻",
      "isPlaceholder": false
    },
    "31": {
      "id": 31,
      "name": "Saudi Arabia",
      "code": "KSA",
      "group": "H",
      "flag": "🇸🇦",
      "isPlaceholder": false
    },
    "32": {
      "id": 32,
      "name": "Uruguay",
      "code": "URU",
      "group": "H",
      "flag": "🇺🇾",
      "isPlaceholder": false
    },
    "33": {
      "id": 33,
      "name": "France",
      "code": "FRA",
      "group": "I",
      "flag": "🇫🇷",
      "isPlaceholder": false
    },
    "34": {
      "id": 34,
      "name": "Senegal",
      "code": "SEN",
      "group": "I",
      "flag": "🇸🇳",
      "isPlaceholder": false
    },
    "35": {
      "id": 35,
      "name": "DR Congo",
      "code": "COD",
      "group": "I",
      "flag": "🇨🇩",
      "isPlaceholder": false
    },
    "36": {
      "id": 36,
      "name": "Norway",
      "code": "NOR",
      "group": "I",
      "flag": "🇳🇴",
      "isPlaceholder": false
    },
    "37": {
      "id": 37,
      "name": "Argentina",
      "code": "ARG",
      "group": "J",
      "flag": "🇦🇷",
      "isPlaceholder": false
    },
    "38": {
      "id": 38,
      "name": "Algeria",
      "code": "ALG",
      "group": "J",
      "flag": "🇩🇿",
      "isPlaceholder": false
    },
    "39": {
      "id": 39,
      "name": "Austria",
      "code": "AUT",
      "group": "J",
      "flag": "🇦🇹",
      "isPlaceholder": false
    },
    "40": {
      "id": 40,
      "name": "Jordan",
      "code": "JOR",
      "group": "J",
      "flag": "🇯🇴",
      "isPlaceholder": false
    },
    "41": {
      "id": 41,
      "name": "Portugal",
      "code": "POR",
      "group": "K",
      "flag": "🇵🇹",
      "isPlaceholder": false
    },
    "42": {
      "id": 42,
      "name": "Iraq",
      "code": "IRQ",
      "group": "K",
      "flag": "🇮🇶",
      "isPlaceholder": false
    },
    "43": {
      "id": 43,
      "name": "Uzbekistan",
      "code": "UZB",
      "group": "K",
      "flag": "🇺🇿",
      "isPlaceholder": false
    },
    "44": {
      "id": 44,
      "name": "Colombia",
      "code": "COL",
      "group": "K",
      "flag": "🇨🇴",
      "isPlaceholder": false
    },
    "45": {
      "id": 45,
      "name": "England",
      "code": "ENG",
      "group": "L",
      "flag": "🏴",
      "isPlaceholder": false
    },
    "46": {
      "id": 46,
      "name": "Croatia",
      "code": "CRO",
      "group": "L",
      "flag": "🇭🇷",
      "isPlaceholder": false
    },
    "47": {
      "id": 47,
      "name": "Ghana",
      "code": "GHA",
      "group": "L",
      "flag": "🇬🇭",
      "isPlaceholder": false
    },
    "48": {
      "id": 48,
      "name": "Panama",
      "code": "PAN",
      "group": "L",
      "flag": "🇵🇦",
      "isPlaceholder": false
    }
  },
  "stages": [
    {
      "id": 1,
      "name": "Group Stage",
      "order": 1
    },
    {
      "id": 2,
      "name": "Round of 32",
      "order": 2
    },
    {
      "id": 3,
      "name": "Round of 16",
      "order": 3
    },
    {
      "id": 4,
      "name": "Quarterfinals",
      "order": 4
    },
    {
      "id": 5,
      "name": "Semifinals",
      "order": 5
    },
    {
      "id": 6,
      "name": "Third Place Playoff",
      "order": 6
    },
    {
      "id": 7,
      "name": "Final",
      "order": 7
    }
  ],
  "matches": [
    {
      "id": 1,
      "matchNumber": 1,
      "homeTeamId": 1,
      "awayTeamId": 2,
      "homeTeam": {
        "id": 1,
        "name": "Mexico",
        "code": "MEX",
        "group": "A",
        "flag": "🇲🇽",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 2,
        "name": "South Africa",
        "code": "RSA",
        "group": "A",
        "flag": "🇿🇦",
        "isPlaceholder": false
      },
      "stadiumId": "mexico-city",
      "cityId": 15,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-11 15:00:00-06",
      "label": "Group A",
      "display": "Mexico vs South Africa",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 2,
      "matchNumber": 2,
      "homeTeamId": 3,
      "awayTeamId": 4,
      "homeTeam": {
        "id": 3,
        "name": "South Korea",
        "code": "KOR",
        "group": "A",
        "flag": "🇰🇷",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 4,
        "name": "Czechia",
        "code": "CZE",
        "group": "A",
        "flag": "🇨🇿",
        "isPlaceholder": false
      },
      "stadiumId": "guadalajara",
      "cityId": 14,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-11 22:00:00-06",
      "label": "Group A",
      "display": "South Korea vs Czechia",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 3,
      "matchNumber": 3,
      "homeTeamId": 5,
      "awayTeamId": 6,
      "homeTeam": {
        "id": 5,
        "name": "Canada",
        "code": "CAN",
        "group": "B",
        "flag": "🇨🇦",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 6,
        "name": "Bosnia and Herzegovina",
        "code": "BIH",
        "group": "B",
        "flag": "🇧🇦",
        "isPlaceholder": false
      },
      "stadiumId": "toronto",
      "cityId": 12,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-12 15:00:00-04",
      "label": "Group B",
      "display": "Canada vs Bosnia and Herzegovina",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 4,
      "matchNumber": 4,
      "homeTeamId": 13,
      "awayTeamId": 14,
      "homeTeam": {
        "id": 13,
        "name": "USA",
        "code": "USA",
        "group": "D",
        "flag": "🇺🇸",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 14,
        "name": "Paraguay",
        "code": "PAR",
        "group": "D",
        "flag": "🇵🇾",
        "isPlaceholder": false
      },
      "stadiumId": "los-angeles",
      "cityId": 6,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-12 21:00:00-07",
      "label": "Group D",
      "display": "USA vs Paraguay",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 5,
      "matchNumber": 5,
      "homeTeamId": 7,
      "awayTeamId": 8,
      "homeTeam": {
        "id": 7,
        "name": "Qatar",
        "code": "QAT",
        "group": "B",
        "flag": "🇶🇦",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 8,
        "name": "Switzerland",
        "code": "SUI",
        "group": "B",
        "flag": "🇨🇭",
        "isPlaceholder": false
      },
      "stadiumId": "san-francisco-bay-area",
      "cityId": 10,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-13 15:00:00-07",
      "label": "Group B",
      "display": "Qatar vs Switzerland",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 6,
      "matchNumber": 6,
      "homeTeamId": 9,
      "awayTeamId": 10,
      "homeTeam": {
        "id": 9,
        "name": "Brazil",
        "code": "BRA",
        "group": "C",
        "flag": "🇧🇷",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 10,
        "name": "Morocco",
        "code": "MAR",
        "group": "C",
        "flag": "🇲🇦",
        "isPlaceholder": false
      },
      "stadiumId": "new-york-new-jersey",
      "cityId": 8,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-13 18:00:00-04",
      "label": "Group C",
      "display": "Brazil vs Morocco",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 7,
      "matchNumber": 7,
      "homeTeamId": 11,
      "awayTeamId": 12,
      "homeTeam": {
        "id": 11,
        "name": "Haiti",
        "code": "HAI",
        "group": "C",
        "flag": "🇭🇹",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 12,
        "name": "Scotland",
        "code": "SCO",
        "group": "C",
        "flag": "🏴",
        "isPlaceholder": false
      },
      "stadiumId": "boston",
      "cityId": 2,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-13 21:00:00-04",
      "label": "Group C",
      "display": "Haiti vs Scotland",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 8,
      "matchNumber": 8,
      "homeTeamId": 15,
      "awayTeamId": 16,
      "homeTeam": {
        "id": 15,
        "name": "Australia",
        "code": "AUS",
        "group": "D",
        "flag": "🇦🇺",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 16,
        "name": "Türkiye",
        "code": "TUR",
        "group": "D",
        "flag": "🇹🇷",
        "isPlaceholder": false
      },
      "stadiumId": "vancouver",
      "cityId": 13,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-14 00:00:00-07",
      "label": "Group D",
      "display": "Australia vs Türkiye",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 9,
      "matchNumber": 9,
      "homeTeamId": 17,
      "awayTeamId": 18,
      "homeTeam": {
        "id": 17,
        "name": "Germany",
        "code": "GER",
        "group": "E",
        "flag": "🇩🇪",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 18,
        "name": "Curaçao",
        "code": "CUR",
        "group": "E",
        "flag": "🇨🇼",
        "isPlaceholder": false
      },
      "stadiumId": "houston",
      "cityId": 4,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-14 13:00:00-05",
      "label": "Group E",
      "display": "Germany vs Curaçao",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 10,
      "matchNumber": 10,
      "homeTeamId": 21,
      "awayTeamId": 22,
      "homeTeam": {
        "id": 21,
        "name": "Netherlands",
        "code": "NED",
        "group": "F",
        "flag": "🇳🇱",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 22,
        "name": "Japan",
        "code": "JPN",
        "group": "F",
        "flag": "🇯🇵",
        "isPlaceholder": false
      },
      "stadiumId": "dallas",
      "cityId": 3,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-14 16:00:00-05",
      "label": "Group F",
      "display": "Netherlands vs Japan",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 11,
      "matchNumber": 11,
      "homeTeamId": 19,
      "awayTeamId": 20,
      "homeTeam": {
        "id": 19,
        "name": "Côte d'Ivoire",
        "code": "CIV",
        "group": "E",
        "flag": "🇨🇮",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 20,
        "name": "Ecuador",
        "code": "ECU",
        "group": "E",
        "flag": "🇪🇨",
        "isPlaceholder": false
      },
      "stadiumId": "philadelphia",
      "cityId": 9,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-14 19:00:00-04",
      "label": "Group E",
      "display": "Côte d'Ivoire vs Ecuador",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 12,
      "matchNumber": 12,
      "homeTeamId": 23,
      "awayTeamId": 24,
      "homeTeam": {
        "id": 23,
        "name": "Sweden",
        "code": "SWE",
        "group": "F",
        "flag": "🇸🇪",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 24,
        "name": "Tunisia",
        "code": "TUN",
        "group": "F",
        "flag": "🇹🇳",
        "isPlaceholder": false
      },
      "stadiumId": "monterrey",
      "cityId": 16,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-14 22:00:00-06",
      "label": "Group F",
      "display": "Sweden vs Tunisia",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 13,
      "matchNumber": 13,
      "homeTeamId": 29,
      "awayTeamId": 30,
      "homeTeam": {
        "id": 29,
        "name": "Spain",
        "code": "ESP",
        "group": "H",
        "flag": "🇪🇸",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 30,
        "name": "Cabo Verde",
        "code": "CPV",
        "group": "H",
        "flag": "🇨🇻",
        "isPlaceholder": false
      },
      "stadiumId": "atlanta",
      "cityId": 1,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-15 12:00:00-04",
      "label": "Group H",
      "display": "Spain vs Cabo Verde",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 14,
      "matchNumber": 14,
      "homeTeamId": 25,
      "awayTeamId": 26,
      "homeTeam": {
        "id": 25,
        "name": "Belgium",
        "code": "BEL",
        "group": "G",
        "flag": "🇧🇪",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 26,
        "name": "Egypt",
        "code": "EGY",
        "group": "G",
        "flag": "🇪🇬",
        "isPlaceholder": false
      },
      "stadiumId": "seattle",
      "cityId": 11,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-15 15:00:00-07",
      "label": "Group G",
      "display": "Belgium vs Egypt",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 15,
      "matchNumber": 15,
      "homeTeamId": 31,
      "awayTeamId": 32,
      "homeTeam": {
        "id": 31,
        "name": "Saudi Arabia",
        "code": "KSA",
        "group": "H",
        "flag": "🇸🇦",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 32,
        "name": "Uruguay",
        "code": "URU",
        "group": "H",
        "flag": "🇺🇾",
        "isPlaceholder": false
      },
      "stadiumId": "miami",
      "cityId": 7,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-15 18:00:00-04",
      "label": "Group H",
      "display": "Saudi Arabia vs Uruguay",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 16,
      "matchNumber": 16,
      "homeTeamId": 27,
      "awayTeamId": 28,
      "homeTeam": {
        "id": 27,
        "name": "IR Iran",
        "code": "IRN",
        "group": "G",
        "flag": "🇮🇷",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 28,
        "name": "New Zealand",
        "code": "NZL",
        "group": "G",
        "flag": "🇳🇿",
        "isPlaceholder": false
      },
      "stadiumId": "los-angeles",
      "cityId": 6,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-15 21:00:00-07",
      "label": "Group G",
      "display": "IR Iran vs New Zealand",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 17,
      "matchNumber": 17,
      "homeTeamId": 33,
      "awayTeamId": 34,
      "homeTeam": {
        "id": 33,
        "name": "France",
        "code": "FRA",
        "group": "I",
        "flag": "🇫🇷",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 34,
        "name": "Senegal",
        "code": "SEN",
        "group": "I",
        "flag": "🇸🇳",
        "isPlaceholder": false
      },
      "stadiumId": "new-york-new-jersey",
      "cityId": 8,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-16 15:00:00-04",
      "label": "Group I",
      "display": "France vs Senegal",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 18,
      "matchNumber": 18,
      "homeTeamId": 35,
      "awayTeamId": 36,
      "homeTeam": {
        "id": 35,
        "name": "DR Congo",
        "code": "COD",
        "group": "I",
        "flag": "🇨🇩",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 36,
        "name": "Norway",
        "code": "NOR",
        "group": "I",
        "flag": "🇳🇴",
        "isPlaceholder": false
      },
      "stadiumId": "boston",
      "cityId": 2,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-16 18:00:00-04",
      "label": "Group I",
      "display": "DR Congo vs Norway",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 19,
      "matchNumber": 19,
      "homeTeamId": 37,
      "awayTeamId": 38,
      "homeTeam": {
        "id": 37,
        "name": "Argentina",
        "code": "ARG",
        "group": "J",
        "flag": "🇦🇷",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 38,
        "name": "Algeria",
        "code": "ALG",
        "group": "J",
        "flag": "🇩🇿",
        "isPlaceholder": false
      },
      "stadiumId": "kansas-city",
      "cityId": 5,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-16 21:00:00-05",
      "label": "Group J",
      "display": "Argentina vs Algeria",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 20,
      "matchNumber": 20,
      "homeTeamId": 39,
      "awayTeamId": 40,
      "homeTeam": {
        "id": 39,
        "name": "Austria",
        "code": "AUT",
        "group": "J",
        "flag": "🇦🇹",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 40,
        "name": "Jordan",
        "code": "JOR",
        "group": "J",
        "flag": "🇯🇴",
        "isPlaceholder": false
      },
      "stadiumId": "san-francisco-bay-area",
      "cityId": 10,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-17 00:00:00-07",
      "label": "Group J",
      "display": "Austria vs Jordan",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 21,
      "matchNumber": 21,
      "homeTeamId": 41,
      "awayTeamId": 42,
      "homeTeam": {
        "id": 41,
        "name": "Portugal",
        "code": "POR",
        "group": "K",
        "flag": "🇵🇹",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 42,
        "name": "Iraq",
        "code": "IRQ",
        "group": "K",
        "flag": "🇮🇶",
        "isPlaceholder": false
      },
      "stadiumId": "houston",
      "cityId": 4,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-17 13:00:00-05",
      "label": "Group K",
      "display": "Portugal vs Iraq",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 22,
      "matchNumber": 22,
      "homeTeamId": 45,
      "awayTeamId": 46,
      "homeTeam": {
        "id": 45,
        "name": "England",
        "code": "ENG",
        "group": "L",
        "flag": "🏴",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 46,
        "name": "Croatia",
        "code": "CRO",
        "group": "L",
        "flag": "🇭🇷",
        "isPlaceholder": false
      },
      "stadiumId": "dallas",
      "cityId": 3,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-17 16:00:00-05",
      "label": "Group L",
      "display": "England vs Croatia",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 23,
      "matchNumber": 23,
      "homeTeamId": 47,
      "awayTeamId": 48,
      "homeTeam": {
        "id": 47,
        "name": "Ghana",
        "code": "GHA",
        "group": "L",
        "flag": "🇬🇭",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 48,
        "name": "Panama",
        "code": "PAN",
        "group": "L",
        "flag": "🇵🇦",
        "isPlaceholder": false
      },
      "stadiumId": "toronto",
      "cityId": 12,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-17 19:00:00-04",
      "label": "Group L",
      "display": "Ghana vs Panama",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 24,
      "matchNumber": 24,
      "homeTeamId": 43,
      "awayTeamId": 44,
      "homeTeam": {
        "id": 43,
        "name": "Uzbekistan",
        "code": "UZB",
        "group": "K",
        "flag": "🇺🇿",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 44,
        "name": "Colombia",
        "code": "COL",
        "group": "K",
        "flag": "🇨🇴",
        "isPlaceholder": false
      },
      "stadiumId": "mexico-city",
      "cityId": 15,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-17 22:00:00-06",
      "label": "Group K",
      "display": "Uzbekistan vs Colombia",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 25,
      "matchNumber": 25,
      "homeTeamId": 4,
      "awayTeamId": 2,
      "homeTeam": {
        "id": 4,
        "name": "Czechia",
        "code": "CZE",
        "group": "A",
        "flag": "🇨🇿",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 2,
        "name": "South Africa",
        "code": "RSA",
        "group": "A",
        "flag": "🇿🇦",
        "isPlaceholder": false
      },
      "stadiumId": "atlanta",
      "cityId": 1,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-18 12:00:00-04",
      "label": "Group A",
      "display": "Czechia vs South Africa",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 26,
      "matchNumber": 26,
      "homeTeamId": 8,
      "awayTeamId": 6,
      "homeTeam": {
        "id": 8,
        "name": "Switzerland",
        "code": "SUI",
        "group": "B",
        "flag": "🇨🇭",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 6,
        "name": "Bosnia and Herzegovina",
        "code": "BIH",
        "group": "B",
        "flag": "🇧🇦",
        "isPlaceholder": false
      },
      "stadiumId": "los-angeles",
      "cityId": 6,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-18 15:00:00-07",
      "label": "Group B",
      "display": "Switzerland vs Bosnia and Herzegovina",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 27,
      "matchNumber": 27,
      "homeTeamId": 5,
      "awayTeamId": 7,
      "homeTeam": {
        "id": 5,
        "name": "Canada",
        "code": "CAN",
        "group": "B",
        "flag": "🇨🇦",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 7,
        "name": "Qatar",
        "code": "QAT",
        "group": "B",
        "flag": "🇶🇦",
        "isPlaceholder": false
      },
      "stadiumId": "vancouver",
      "cityId": 13,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-18 18:00:00-07",
      "label": "Group B",
      "display": "Canada vs Qatar",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 28,
      "matchNumber": 28,
      "homeTeamId": 1,
      "awayTeamId": 3,
      "homeTeam": {
        "id": 1,
        "name": "Mexico",
        "code": "MEX",
        "group": "A",
        "flag": "🇲🇽",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 3,
        "name": "South Korea",
        "code": "KOR",
        "group": "A",
        "flag": "🇰🇷",
        "isPlaceholder": false
      },
      "stadiumId": "guadalajara",
      "cityId": 14,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-18 21:00:00-06",
      "label": "Group A",
      "display": "Mexico vs South Korea",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 29,
      "matchNumber": 29,
      "homeTeamId": 13,
      "awayTeamId": 15,
      "homeTeam": {
        "id": 13,
        "name": "USA",
        "code": "USA",
        "group": "D",
        "flag": "🇺🇸",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 15,
        "name": "Australia",
        "code": "AUS",
        "group": "D",
        "flag": "🇦🇺",
        "isPlaceholder": false
      },
      "stadiumId": "seattle",
      "cityId": 11,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-19 15:00:00-07",
      "label": "Group D",
      "display": "USA vs Australia",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 30,
      "matchNumber": 30,
      "homeTeamId": 12,
      "awayTeamId": 10,
      "homeTeam": {
        "id": 12,
        "name": "Scotland",
        "code": "SCO",
        "group": "C",
        "flag": "🏴",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 10,
        "name": "Morocco",
        "code": "MAR",
        "group": "C",
        "flag": "🇲🇦",
        "isPlaceholder": false
      },
      "stadiumId": "boston",
      "cityId": 2,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-19 18:00:00-04",
      "label": "Group C",
      "display": "Scotland vs Morocco",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 31,
      "matchNumber": 31,
      "homeTeamId": 9,
      "awayTeamId": 11,
      "homeTeam": {
        "id": 9,
        "name": "Brazil",
        "code": "BRA",
        "group": "C",
        "flag": "🇧🇷",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 11,
        "name": "Haiti",
        "code": "HAI",
        "group": "C",
        "flag": "🇭🇹",
        "isPlaceholder": false
      },
      "stadiumId": "philadelphia",
      "cityId": 9,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-19 21:00:00-04",
      "label": "Group C",
      "display": "Brazil vs Haiti",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 32,
      "matchNumber": 32,
      "homeTeamId": 16,
      "awayTeamId": 14,
      "homeTeam": {
        "id": 16,
        "name": "Türkiye",
        "code": "TUR",
        "group": "D",
        "flag": "🇹🇷",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 14,
        "name": "Paraguay",
        "code": "PAR",
        "group": "D",
        "flag": "🇵🇾",
        "isPlaceholder": false
      },
      "stadiumId": "san-francisco-bay-area",
      "cityId": 10,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-20 00:00:00-07",
      "label": "Group D",
      "display": "Türkiye vs Paraguay",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 33,
      "matchNumber": 33,
      "homeTeamId": 21,
      "awayTeamId": 23,
      "homeTeam": {
        "id": 21,
        "name": "Netherlands",
        "code": "NED",
        "group": "F",
        "flag": "🇳🇱",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 23,
        "name": "Sweden",
        "code": "SWE",
        "group": "F",
        "flag": "🇸🇪",
        "isPlaceholder": false
      },
      "stadiumId": "houston",
      "cityId": 4,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-20 13:00:00-05",
      "label": "Group F",
      "display": "Netherlands vs Sweden",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 34,
      "matchNumber": 34,
      "homeTeamId": 17,
      "awayTeamId": 19,
      "homeTeam": {
        "id": 17,
        "name": "Germany",
        "code": "GER",
        "group": "E",
        "flag": "🇩🇪",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 19,
        "name": "Côte d'Ivoire",
        "code": "CIV",
        "group": "E",
        "flag": "🇨🇮",
        "isPlaceholder": false
      },
      "stadiumId": "toronto",
      "cityId": 12,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-20 16:00:00-04",
      "label": "Group E",
      "display": "Germany vs Côte d'Ivoire",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 35,
      "matchNumber": 35,
      "homeTeamId": 20,
      "awayTeamId": 18,
      "homeTeam": {
        "id": 20,
        "name": "Ecuador",
        "code": "ECU",
        "group": "E",
        "flag": "🇪🇨",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 18,
        "name": "Curaçao",
        "code": "CUR",
        "group": "E",
        "flag": "🇨🇼",
        "isPlaceholder": false
      },
      "stadiumId": "kansas-city",
      "cityId": 5,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-20 20:00:00-05",
      "label": "Group E",
      "display": "Ecuador vs Curaçao",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 36,
      "matchNumber": 36,
      "homeTeamId": 24,
      "awayTeamId": 22,
      "homeTeam": {
        "id": 24,
        "name": "Tunisia",
        "code": "TUN",
        "group": "F",
        "flag": "🇹🇳",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 22,
        "name": "Japan",
        "code": "JPN",
        "group": "F",
        "flag": "🇯🇵",
        "isPlaceholder": false
      },
      "stadiumId": "monterrey",
      "cityId": 16,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-21 00:00:00-06",
      "label": "Group F",
      "display": "Tunisia vs Japan",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 37,
      "matchNumber": 37,
      "homeTeamId": 29,
      "awayTeamId": 31,
      "homeTeam": {
        "id": 29,
        "name": "Spain",
        "code": "ESP",
        "group": "H",
        "flag": "🇪🇸",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 31,
        "name": "Saudi Arabia",
        "code": "KSA",
        "group": "H",
        "flag": "🇸🇦",
        "isPlaceholder": false
      },
      "stadiumId": "atlanta",
      "cityId": 1,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-21 12:00:00-04",
      "label": "Group H",
      "display": "Spain vs Saudi Arabia",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 38,
      "matchNumber": 38,
      "homeTeamId": 25,
      "awayTeamId": 27,
      "homeTeam": {
        "id": 25,
        "name": "Belgium",
        "code": "BEL",
        "group": "G",
        "flag": "🇧🇪",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 27,
        "name": "IR Iran",
        "code": "IRN",
        "group": "G",
        "flag": "🇮🇷",
        "isPlaceholder": false
      },
      "stadiumId": "los-angeles",
      "cityId": 6,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-21 15:00:00-07",
      "label": "Group G",
      "display": "Belgium vs IR Iran",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 39,
      "matchNumber": 39,
      "homeTeamId": 32,
      "awayTeamId": 30,
      "homeTeam": {
        "id": 32,
        "name": "Uruguay",
        "code": "URU",
        "group": "H",
        "flag": "🇺🇾",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 30,
        "name": "Cabo Verde",
        "code": "CPV",
        "group": "H",
        "flag": "🇨🇻",
        "isPlaceholder": false
      },
      "stadiumId": "miami",
      "cityId": 7,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-21 18:00:00-04",
      "label": "Group H",
      "display": "Uruguay vs Cabo Verde",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 40,
      "matchNumber": 40,
      "homeTeamId": 28,
      "awayTeamId": 26,
      "homeTeam": {
        "id": 28,
        "name": "New Zealand",
        "code": "NZL",
        "group": "G",
        "flag": "🇳🇿",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 26,
        "name": "Egypt",
        "code": "EGY",
        "group": "G",
        "flag": "🇪🇬",
        "isPlaceholder": false
      },
      "stadiumId": "vancouver",
      "cityId": 13,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-21 21:00:00-07",
      "label": "Group G",
      "display": "New Zealand vs Egypt",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 41,
      "matchNumber": 41,
      "homeTeamId": 37,
      "awayTeamId": 39,
      "homeTeam": {
        "id": 37,
        "name": "Argentina",
        "code": "ARG",
        "group": "J",
        "flag": "🇦🇷",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 39,
        "name": "Austria",
        "code": "AUT",
        "group": "J",
        "flag": "🇦🇹",
        "isPlaceholder": false
      },
      "stadiumId": "dallas",
      "cityId": 3,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-22 13:00:00-05",
      "label": "Group J",
      "display": "Argentina vs Austria",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 42,
      "matchNumber": 42,
      "homeTeamId": 33,
      "awayTeamId": 35,
      "homeTeam": {
        "id": 33,
        "name": "France",
        "code": "FRA",
        "group": "I",
        "flag": "🇫🇷",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 35,
        "name": "DR Congo",
        "code": "COD",
        "group": "I",
        "flag": "🇨🇩",
        "isPlaceholder": false
      },
      "stadiumId": "philadelphia",
      "cityId": 9,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-22 17:00:00-04",
      "label": "Group I",
      "display": "France vs DR Congo",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 43,
      "matchNumber": 43,
      "homeTeamId": 36,
      "awayTeamId": 34,
      "homeTeam": {
        "id": 36,
        "name": "Norway",
        "code": "NOR",
        "group": "I",
        "flag": "🇳🇴",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 34,
        "name": "Senegal",
        "code": "SEN",
        "group": "I",
        "flag": "🇸🇳",
        "isPlaceholder": false
      },
      "stadiumId": "new-york-new-jersey",
      "cityId": 8,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-22 20:00:00-04",
      "label": "Group I",
      "display": "Norway vs Senegal",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 44,
      "matchNumber": 44,
      "homeTeamId": 40,
      "awayTeamId": 38,
      "homeTeam": {
        "id": 40,
        "name": "Jordan",
        "code": "JOR",
        "group": "J",
        "flag": "🇯🇴",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 38,
        "name": "Algeria",
        "code": "ALG",
        "group": "J",
        "flag": "🇩🇿",
        "isPlaceholder": false
      },
      "stadiumId": "san-francisco-bay-area",
      "cityId": 10,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-22 23:00:00-07",
      "label": "Group J",
      "display": "Jordan vs Algeria",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 45,
      "matchNumber": 45,
      "homeTeamId": 41,
      "awayTeamId": 43,
      "homeTeam": {
        "id": 41,
        "name": "Portugal",
        "code": "POR",
        "group": "K",
        "flag": "🇵🇹",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 43,
        "name": "Uzbekistan",
        "code": "UZB",
        "group": "K",
        "flag": "🇺🇿",
        "isPlaceholder": false
      },
      "stadiumId": "houston",
      "cityId": 4,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-23 13:00:00-05",
      "label": "Group K",
      "display": "Portugal vs Uzbekistan",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 46,
      "matchNumber": 46,
      "homeTeamId": 45,
      "awayTeamId": 47,
      "homeTeam": {
        "id": 45,
        "name": "England",
        "code": "ENG",
        "group": "L",
        "flag": "🏴",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 47,
        "name": "Ghana",
        "code": "GHA",
        "group": "L",
        "flag": "🇬🇭",
        "isPlaceholder": false
      },
      "stadiumId": "boston",
      "cityId": 2,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-23 16:00:00-04",
      "label": "Group L",
      "display": "England vs Ghana",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 47,
      "matchNumber": 47,
      "homeTeamId": 48,
      "awayTeamId": 46,
      "homeTeam": {
        "id": 48,
        "name": "Panama",
        "code": "PAN",
        "group": "L",
        "flag": "🇵🇦",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 46,
        "name": "Croatia",
        "code": "CRO",
        "group": "L",
        "flag": "🇭🇷",
        "isPlaceholder": false
      },
      "stadiumId": "toronto",
      "cityId": 12,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-23 19:00:00-04",
      "label": "Group L",
      "display": "Panama vs Croatia",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 48,
      "matchNumber": 48,
      "homeTeamId": 44,
      "awayTeamId": 42,
      "homeTeam": {
        "id": 44,
        "name": "Colombia",
        "code": "COL",
        "group": "K",
        "flag": "🇨🇴",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 42,
        "name": "Iraq",
        "code": "IRQ",
        "group": "K",
        "flag": "🇮🇶",
        "isPlaceholder": false
      },
      "stadiumId": "guadalajara",
      "cityId": 14,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-23 22:00:00-06",
      "label": "Group K",
      "display": "Colombia vs Iraq",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 49,
      "matchNumber": 49,
      "homeTeamId": 8,
      "awayTeamId": 5,
      "homeTeam": {
        "id": 8,
        "name": "Switzerland",
        "code": "SUI",
        "group": "B",
        "flag": "🇨🇭",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 5,
        "name": "Canada",
        "code": "CAN",
        "group": "B",
        "flag": "🇨🇦",
        "isPlaceholder": false
      },
      "stadiumId": "vancouver",
      "cityId": 13,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-24 15:00:00-07",
      "label": "Group B",
      "display": "Switzerland vs Canada",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 50,
      "matchNumber": 50,
      "homeTeamId": 6,
      "awayTeamId": 7,
      "homeTeam": {
        "id": 6,
        "name": "Bosnia and Herzegovina",
        "code": "BIH",
        "group": "B",
        "flag": "🇧🇦",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 7,
        "name": "Qatar",
        "code": "QAT",
        "group": "B",
        "flag": "🇶🇦",
        "isPlaceholder": false
      },
      "stadiumId": "seattle",
      "cityId": 11,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-24 15:00:00-07",
      "label": "Group B",
      "display": "Bosnia and Herzegovina vs Qatar",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 51,
      "matchNumber": 51,
      "homeTeamId": 12,
      "awayTeamId": 9,
      "homeTeam": {
        "id": 12,
        "name": "Scotland",
        "code": "SCO",
        "group": "C",
        "flag": "🏴",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 9,
        "name": "Brazil",
        "code": "BRA",
        "group": "C",
        "flag": "🇧🇷",
        "isPlaceholder": false
      },
      "stadiumId": "miami",
      "cityId": 7,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-24 18:00:00-04",
      "label": "Group C",
      "display": "Scotland vs Brazil",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 52,
      "matchNumber": 52,
      "homeTeamId": 10,
      "awayTeamId": 11,
      "homeTeam": {
        "id": 10,
        "name": "Morocco",
        "code": "MAR",
        "group": "C",
        "flag": "🇲🇦",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 11,
        "name": "Haiti",
        "code": "HAI",
        "group": "C",
        "flag": "🇭🇹",
        "isPlaceholder": false
      },
      "stadiumId": "atlanta",
      "cityId": 1,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-24 18:00:00-04",
      "label": "Group C",
      "display": "Morocco vs Haiti",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 53,
      "matchNumber": 53,
      "homeTeamId": 4,
      "awayTeamId": 1,
      "homeTeam": {
        "id": 4,
        "name": "Czechia",
        "code": "CZE",
        "group": "A",
        "flag": "🇨🇿",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 1,
        "name": "Mexico",
        "code": "MEX",
        "group": "A",
        "flag": "🇲🇽",
        "isPlaceholder": false
      },
      "stadiumId": "mexico-city",
      "cityId": 15,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-24 21:00:00-06",
      "label": "Group A",
      "display": "Czechia vs Mexico",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 54,
      "matchNumber": 54,
      "homeTeamId": 2,
      "awayTeamId": 3,
      "homeTeam": {
        "id": 2,
        "name": "South Africa",
        "code": "RSA",
        "group": "A",
        "flag": "🇿🇦",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 3,
        "name": "South Korea",
        "code": "KOR",
        "group": "A",
        "flag": "🇰🇷",
        "isPlaceholder": false
      },
      "stadiumId": "monterrey",
      "cityId": 16,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-24 21:00:00-06",
      "label": "Group A",
      "display": "South Africa vs South Korea",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 55,
      "matchNumber": 55,
      "homeTeamId": 18,
      "awayTeamId": 19,
      "homeTeam": {
        "id": 18,
        "name": "Curaçao",
        "code": "CUR",
        "group": "E",
        "flag": "🇨🇼",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 19,
        "name": "Côte d'Ivoire",
        "code": "CIV",
        "group": "E",
        "flag": "🇨🇮",
        "isPlaceholder": false
      },
      "stadiumId": "philadelphia",
      "cityId": 9,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-25 16:00:00-04",
      "label": "Group E",
      "display": "Curaçao vs Côte d'Ivoire",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 56,
      "matchNumber": 56,
      "homeTeamId": 20,
      "awayTeamId": 17,
      "homeTeam": {
        "id": 20,
        "name": "Ecuador",
        "code": "ECU",
        "group": "E",
        "flag": "🇪🇨",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 17,
        "name": "Germany",
        "code": "GER",
        "group": "E",
        "flag": "🇩🇪",
        "isPlaceholder": false
      },
      "stadiumId": "new-york-new-jersey",
      "cityId": 8,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-25 16:00:00-04",
      "label": "Group E",
      "display": "Ecuador vs Germany",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 57,
      "matchNumber": 57,
      "homeTeamId": 22,
      "awayTeamId": 23,
      "homeTeam": {
        "id": 22,
        "name": "Japan",
        "code": "JPN",
        "group": "F",
        "flag": "🇯🇵",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 23,
        "name": "Sweden",
        "code": "SWE",
        "group": "F",
        "flag": "🇸🇪",
        "isPlaceholder": false
      },
      "stadiumId": "dallas",
      "cityId": 3,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-25 19:00:00-05",
      "label": "Group F",
      "display": "Japan vs Sweden",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 58,
      "matchNumber": 58,
      "homeTeamId": 24,
      "awayTeamId": 21,
      "homeTeam": {
        "id": 24,
        "name": "Tunisia",
        "code": "TUN",
        "group": "F",
        "flag": "🇹🇳",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 21,
        "name": "Netherlands",
        "code": "NED",
        "group": "F",
        "flag": "🇳🇱",
        "isPlaceholder": false
      },
      "stadiumId": "kansas-city",
      "cityId": 5,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-25 19:00:00-05",
      "label": "Group F",
      "display": "Tunisia vs Netherlands",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 59,
      "matchNumber": 59,
      "homeTeamId": 16,
      "awayTeamId": 13,
      "homeTeam": {
        "id": 16,
        "name": "Türkiye",
        "code": "TUR",
        "group": "D",
        "flag": "🇹🇷",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 13,
        "name": "USA",
        "code": "USA",
        "group": "D",
        "flag": "🇺🇸",
        "isPlaceholder": false
      },
      "stadiumId": "los-angeles",
      "cityId": 6,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-25 22:00:00-07",
      "label": "Group D",
      "display": "Türkiye vs USA",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 60,
      "matchNumber": 60,
      "homeTeamId": 14,
      "awayTeamId": 15,
      "homeTeam": {
        "id": 14,
        "name": "Paraguay",
        "code": "PAR",
        "group": "D",
        "flag": "🇵🇾",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 15,
        "name": "Australia",
        "code": "AUS",
        "group": "D",
        "flag": "🇦🇺",
        "isPlaceholder": false
      },
      "stadiumId": "san-francisco-bay-area",
      "cityId": 10,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-25 22:00:00-07",
      "label": "Group D",
      "display": "Paraguay vs Australia",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 61,
      "matchNumber": 61,
      "homeTeamId": 36,
      "awayTeamId": 33,
      "homeTeam": {
        "id": 36,
        "name": "Norway",
        "code": "NOR",
        "group": "I",
        "flag": "🇳🇴",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 33,
        "name": "France",
        "code": "FRA",
        "group": "I",
        "flag": "🇫🇷",
        "isPlaceholder": false
      },
      "stadiumId": "boston",
      "cityId": 2,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-26 15:00:00-04",
      "label": "Group I",
      "display": "Norway vs France",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 62,
      "matchNumber": 62,
      "homeTeamId": 34,
      "awayTeamId": 35,
      "homeTeam": {
        "id": 34,
        "name": "Senegal",
        "code": "SEN",
        "group": "I",
        "flag": "🇸🇳",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 35,
        "name": "DR Congo",
        "code": "COD",
        "group": "I",
        "flag": "🇨🇩",
        "isPlaceholder": false
      },
      "stadiumId": "toronto",
      "cityId": 12,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-26 15:00:00-04",
      "label": "Group I",
      "display": "Senegal vs DR Congo",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 63,
      "matchNumber": 63,
      "homeTeamId": 30,
      "awayTeamId": 31,
      "homeTeam": {
        "id": 30,
        "name": "Cabo Verde",
        "code": "CPV",
        "group": "H",
        "flag": "🇨🇻",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 31,
        "name": "Saudi Arabia",
        "code": "KSA",
        "group": "H",
        "flag": "🇸🇦",
        "isPlaceholder": false
      },
      "stadiumId": "houston",
      "cityId": 4,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-26 20:00:00-05",
      "label": "Group H",
      "display": "Cabo Verde vs Saudi Arabia",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 64,
      "matchNumber": 64,
      "homeTeamId": 32,
      "awayTeamId": 29,
      "homeTeam": {
        "id": 32,
        "name": "Uruguay",
        "code": "URU",
        "group": "H",
        "flag": "🇺🇾",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 29,
        "name": "Spain",
        "code": "ESP",
        "group": "H",
        "flag": "🇪🇸",
        "isPlaceholder": false
      },
      "stadiumId": "guadalajara",
      "cityId": 14,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-26 20:00:00-06",
      "label": "Group H",
      "display": "Uruguay vs Spain",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 65,
      "matchNumber": 65,
      "homeTeamId": 26,
      "awayTeamId": 27,
      "homeTeam": {
        "id": 26,
        "name": "Egypt",
        "code": "EGY",
        "group": "G",
        "flag": "🇪🇬",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 27,
        "name": "IR Iran",
        "code": "IRN",
        "group": "G",
        "flag": "🇮🇷",
        "isPlaceholder": false
      },
      "stadiumId": "seattle",
      "cityId": 11,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-26 23:00:00-07",
      "label": "Group G",
      "display": "Egypt vs IR Iran",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 66,
      "matchNumber": 66,
      "homeTeamId": 28,
      "awayTeamId": 25,
      "homeTeam": {
        "id": 28,
        "name": "New Zealand",
        "code": "NZL",
        "group": "G",
        "flag": "🇳🇿",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 25,
        "name": "Belgium",
        "code": "BEL",
        "group": "G",
        "flag": "🇧🇪",
        "isPlaceholder": false
      },
      "stadiumId": "vancouver",
      "cityId": 13,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-26 23:00:00-07",
      "label": "Group G",
      "display": "New Zealand vs Belgium",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 67,
      "matchNumber": 67,
      "homeTeamId": 48,
      "awayTeamId": 45,
      "homeTeam": {
        "id": 48,
        "name": "Panama",
        "code": "PAN",
        "group": "L",
        "flag": "🇵🇦",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 45,
        "name": "England",
        "code": "ENG",
        "group": "L",
        "flag": "🏴",
        "isPlaceholder": false
      },
      "stadiumId": "new-york-new-jersey",
      "cityId": 8,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-27 17:00:00-04",
      "label": "Group L",
      "display": "Panama vs England",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 68,
      "matchNumber": 68,
      "homeTeamId": 46,
      "awayTeamId": 47,
      "homeTeam": {
        "id": 46,
        "name": "Croatia",
        "code": "CRO",
        "group": "L",
        "flag": "🇭🇷",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 47,
        "name": "Ghana",
        "code": "GHA",
        "group": "L",
        "flag": "🇬🇭",
        "isPlaceholder": false
      },
      "stadiumId": "philadelphia",
      "cityId": 9,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-27 17:00:00-04",
      "label": "Group L",
      "display": "Croatia vs Ghana",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 69,
      "matchNumber": 69,
      "homeTeamId": 44,
      "awayTeamId": 41,
      "homeTeam": {
        "id": 44,
        "name": "Colombia",
        "code": "COL",
        "group": "K",
        "flag": "🇨🇴",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 41,
        "name": "Portugal",
        "code": "POR",
        "group": "K",
        "flag": "🇵🇹",
        "isPlaceholder": false
      },
      "stadiumId": "miami",
      "cityId": 7,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-27 19:30:00-04",
      "label": "Group K",
      "display": "Colombia vs Portugal",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 70,
      "matchNumber": 70,
      "homeTeamId": 42,
      "awayTeamId": 43,
      "homeTeam": {
        "id": 42,
        "name": "Iraq",
        "code": "IRQ",
        "group": "K",
        "flag": "🇮🇶",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 43,
        "name": "Uzbekistan",
        "code": "UZB",
        "group": "K",
        "flag": "🇺🇿",
        "isPlaceholder": false
      },
      "stadiumId": "atlanta",
      "cityId": 1,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-27 19:30:00-04",
      "label": "Group K",
      "display": "Iraq vs Uzbekistan",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 71,
      "matchNumber": 71,
      "homeTeamId": 38,
      "awayTeamId": 39,
      "homeTeam": {
        "id": 38,
        "name": "Algeria",
        "code": "ALG",
        "group": "J",
        "flag": "🇩🇿",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 39,
        "name": "Austria",
        "code": "AUT",
        "group": "J",
        "flag": "🇦🇹",
        "isPlaceholder": false
      },
      "stadiumId": "kansas-city",
      "cityId": 5,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-27 22:00:00-05",
      "label": "Group J",
      "display": "Algeria vs Austria",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 72,
      "matchNumber": 72,
      "homeTeamId": 40,
      "awayTeamId": 37,
      "homeTeam": {
        "id": 40,
        "name": "Jordan",
        "code": "JOR",
        "group": "J",
        "flag": "🇯🇴",
        "isPlaceholder": false
      },
      "awayTeam": {
        "id": 37,
        "name": "Argentina",
        "code": "ARG",
        "group": "J",
        "flag": "🇦🇷",
        "isPlaceholder": false
      },
      "stadiumId": "dallas",
      "cityId": 3,
      "stage": "Group Stage",
      "stageOrder": 1,
      "kickoff": "2026-06-27 22:00:00-05",
      "label": "Group J",
      "display": "Jordan vs Argentina",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 73,
      "matchNumber": 73,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "los-angeles",
      "cityId": 6,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-06-28 15:00:00-07",
      "label": "2A vs 2B",
      "display": "2A vs 2B",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 74,
      "matchNumber": 74,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "houston",
      "cityId": 4,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-06-29 13:00:00-05",
      "label": "1C vs 2F",
      "display": "1C vs 2F",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 75,
      "matchNumber": 75,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "boston",
      "cityId": 2,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-06-29 16:30:00-04",
      "label": "1E vs 3ABCDF",
      "display": "1E vs 3ABCDF",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 76,
      "matchNumber": 76,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "monterrey",
      "cityId": 16,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-06-29 21:00:00-06",
      "label": "1F vs 2C",
      "display": "1F vs 2C",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 77,
      "matchNumber": 77,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "dallas",
      "cityId": 3,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-06-30 13:00:00-05",
      "label": "2E vs 2I",
      "display": "2E vs 2I",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 78,
      "matchNumber": 78,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "new-york-new-jersey",
      "cityId": 8,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-06-30 17:00:00-04",
      "label": "1I vs 3CDFGH",
      "display": "1I vs 3CDFGH",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 79,
      "matchNumber": 79,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "mexico-city",
      "cityId": 15,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-06-30 21:00:00-06",
      "label": "1A vs 3CEFHI",
      "display": "1A vs 3CEFHI",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 80,
      "matchNumber": 80,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "atlanta",
      "cityId": 1,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-07-01 12:00:00-04",
      "label": "1L vs 3EHIJK",
      "display": "1L vs 3EHIJK",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 81,
      "matchNumber": 81,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "seattle",
      "cityId": 11,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-07-01 16:00:00-07",
      "label": "1G vs 3AEHIJ",
      "display": "1G vs 3AEHIJ",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 82,
      "matchNumber": 82,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "san-francisco-bay-area",
      "cityId": 10,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-07-01 20:00:00-07",
      "label": "1D vs 3BEFIJ",
      "display": "1D vs 3BEFIJ",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 83,
      "matchNumber": 83,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "los-angeles",
      "cityId": 6,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-07-02 15:00:00-07",
      "label": "1H vs 2J",
      "display": "1H vs 2J",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 84,
      "matchNumber": 84,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "toronto",
      "cityId": 12,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-07-02 19:00:00-04",
      "label": "2K vs 2L",
      "display": "2K vs 2L",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 85,
      "matchNumber": 85,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "vancouver",
      "cityId": 13,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-07-02 23:00:00-07",
      "label": "1B vs 3EFGIJ",
      "display": "1B vs 3EFGIJ",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 86,
      "matchNumber": 86,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "dallas",
      "cityId": 3,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-07-03 14:00:00-05",
      "label": "2D vs 2G",
      "display": "2D vs 2G",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 87,
      "matchNumber": 87,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "miami",
      "cityId": 7,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-07-03 18:00:00-04",
      "label": "1J vs 2H",
      "display": "1J vs 2H",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 88,
      "matchNumber": 88,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "kansas-city",
      "cityId": 5,
      "stage": "Round of 32",
      "stageOrder": 2,
      "kickoff": "2026-07-03 21:30:00-05",
      "label": "1K vs 3DEIJL",
      "display": "1K vs 3DEIJL",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 89,
      "matchNumber": 89,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "houston",
      "cityId": 4,
      "stage": "Round of 16",
      "stageOrder": 3,
      "kickoff": "2026-07-04 13:00:00-05",
      "label": "W73 vs W75",
      "display": "W73 vs W75",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 90,
      "matchNumber": 90,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "philadelphia",
      "cityId": 9,
      "stage": "Round of 16",
      "stageOrder": 3,
      "kickoff": "2026-07-04 17:00:00-04",
      "label": "W74 vs W77",
      "display": "W74 vs W77",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 91,
      "matchNumber": 91,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "new-york-new-jersey",
      "cityId": 8,
      "stage": "Round of 16",
      "stageOrder": 3,
      "kickoff": "2026-07-05 16:00:00-04",
      "label": "W76 vs W78",
      "display": "W76 vs W78",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 92,
      "matchNumber": 92,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "mexico-city",
      "cityId": 15,
      "stage": "Round of 16",
      "stageOrder": 3,
      "kickoff": "2026-07-05 20:00:00-06",
      "label": "W79 vs W80",
      "display": "W79 vs W80",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 93,
      "matchNumber": 93,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "dallas",
      "cityId": 3,
      "stage": "Round of 16",
      "stageOrder": 3,
      "kickoff": "2026-07-06 15:00:00-05",
      "label": "W83 vs W84",
      "display": "W83 vs W84",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 94,
      "matchNumber": 94,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "seattle",
      "cityId": 11,
      "stage": "Round of 16",
      "stageOrder": 3,
      "kickoff": "2026-07-06 20:00:00-07",
      "label": "W81 vs W82",
      "display": "W81 vs W82",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 95,
      "matchNumber": 95,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "atlanta",
      "cityId": 1,
      "stage": "Round of 16",
      "stageOrder": 3,
      "kickoff": "2026-07-07 12:00:00-04",
      "label": "W86 vs W88",
      "display": "W86 vs W88",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 96,
      "matchNumber": 96,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "vancouver",
      "cityId": 13,
      "stage": "Round of 16",
      "stageOrder": 3,
      "kickoff": "2026-07-07 16:00:00-07",
      "label": "W85 vs W87",
      "display": "W85 vs W87",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 97,
      "matchNumber": 97,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "boston",
      "cityId": 2,
      "stage": "Quarterfinals",
      "stageOrder": 4,
      "kickoff": "2026-07-09 16:00:00-04",
      "label": "W89 vs W90",
      "display": "W89 vs W90",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 98,
      "matchNumber": 98,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "los-angeles",
      "cityId": 6,
      "stage": "Quarterfinals",
      "stageOrder": 4,
      "kickoff": "2026-07-10 15:00:00-07",
      "label": "W93 vs W94",
      "display": "W93 vs W94",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 99,
      "matchNumber": 99,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "miami",
      "cityId": 7,
      "stage": "Quarterfinals",
      "stageOrder": 4,
      "kickoff": "2026-07-11 17:00:00-04",
      "label": "W91 vs W92",
      "display": "W91 vs W92",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 100,
      "matchNumber": 100,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "kansas-city",
      "cityId": 5,
      "stage": "Quarterfinals",
      "stageOrder": 4,
      "kickoff": "2026-07-11 21:00:00-05",
      "label": "W95 vs W96",
      "display": "W95 vs W96",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 101,
      "matchNumber": 101,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "dallas",
      "cityId": 3,
      "stage": "Semifinals",
      "stageOrder": 5,
      "kickoff": "2026-07-14 15:00:00-05",
      "label": "W97 vs W98",
      "display": "W97 vs W98",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 102,
      "matchNumber": 102,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "atlanta",
      "cityId": 1,
      "stage": "Semifinals",
      "stageOrder": 5,
      "kickoff": "2026-07-15 15:00:00-04",
      "label": "W99 vs W100",
      "display": "W99 vs W100",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 103,
      "matchNumber": 103,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "miami",
      "cityId": 7,
      "stage": "Third Place Playoff",
      "stageOrder": 6,
      "kickoff": "2026-07-18 17:00:00-04",
      "label": "RU101 vs RU102",
      "display": "RU101 vs RU102",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    },
    {
      "id": 104,
      "matchNumber": 104,
      "homeTeamId": null,
      "awayTeamId": null,
      "homeTeam": null,
      "awayTeam": null,
      "stadiumId": "new-york-new-jersey",
      "cityId": 8,
      "stage": "Final",
      "stageOrder": 7,
      "kickoff": "2026-07-19 15:00:00-04",
      "label": "W101 vs W102",
      "display": "W101 vs W102",
      "status": "upcoming",
      "statusShort": "NS",
      "statusLabel": "Scheduled",
      "goalsHome": null,
      "goalsAway": null,
      "winner": null,
      "weather": "TBC"
    }
  ]
};
