/*
  World Cup 2026 Map — sample data for the cinematic prototype.
  Replace match objects later with official fixture data.
*/

window.WC_DATA = {
  meta: {
    title: "World Cup 2026 Map",
    defaultTheme: "dark",
    note: "Prototype data for UI/UX testing before official fixtures are connected."
  },

  teams: {
    USA: { name: "United States", flag: "🇺🇸" },
    MEX: { name: "Mexico", flag: "🇲🇽" },
    CAN: { name: "Canada", flag: "🇨🇦" },
    BRA: { name: "Brazil", flag: "🇧🇷" },
    ARG: { name: "Argentina", flag: "🇦🇷" },
    FRA: { name: "France", flag: "🇫🇷" },
    ESP: { name: "Spain", flag: "🇪🇸" },
    ENG: { name: "England", flag: "🏴" },
    GER: { name: "Germany", flag: "🇩🇪" },
    JPN: { name: "Japan", flag: "🇯🇵" },
    KOR: { name: "Korea Republic", flag: "🇰🇷" },
    MAR: { name: "Morocco", flag: "🇲🇦" },
    SEN: { name: "Senegal", flag: "🇸🇳" },
    NED: { name: "Netherlands", flag: "🇳🇱" },
    POR: { name: "Portugal", flag: "🇵🇹" },
    URU: { name: "Uruguay", flag: "🇺🇾" },
    COL: { name: "Colombia", flag: "🇨🇴" },
    AUS: { name: "Australia", flag: "🇦🇺" },
    QAT: { name: "Qatar", flag: "🇶🇦" },
    GHA: { name: "Ghana", flag: "🇬🇭" },
    ITA: { name: "Italy", flag: "🇮🇹" },
    CRO: { name: "Croatia", flag: "🇭🇷" },
    BEL: { name: "Belgium", flag: "🇧🇪" },
    SUI: { name: "Switzerland", flag: "🇨🇭" }
  },

  stadiums: [
    {
      id: "vancouver",
      name: "BC Place",
      city: "Vancouver",
      country: "Canada",
      countryFlag: "🇨🇦",
      region: "West Coast",
      capacity: 54000,
      lat: 49.2767,
      lng: -123.1119,
      status: "upcoming",
      image: "assets/stadiums/vancouver.jpg",
      label: { dx: -260, dy: -52, anchor: "end" }
    },
    {
      id: "seattle",
      name: "Lumen Field",
      city: "Seattle",
      country: "United States",
      countryFlag: "🇺🇸",
      region: "West Coast",
      capacity: 69000,
      lat: 47.5952,
      lng: -122.3316,
      status: "upcoming",
      image: "assets/stadiums/seattle.jpg",
      label: { dx: -245, dy: 34, anchor: "end" }
    },
    {
      id: "san-francisco",
      name: "Levi's Stadium",
      city: "San Francisco Bay Area",
      country: "United States",
      countryFlag: "🇺🇸",
      region: "West Coast",
      capacity: 71000,
      lat: 37.4030,
      lng: -121.9700,
      status: "upcoming",
      image: "assets/stadiums/san-francisco.jpg",
      label: { dx: -250, dy: -18, anchor: "end" }
    },
    {
      id: "los-angeles",
      name: "SoFi Stadium",
      city: "Los Angeles",
      country: "United States",
      countryFlag: "🇺🇸",
      region: "West Coast",
      capacity: 70000,
      lat: 33.9535,
      lng: -118.3392,
      status: "live",
      image: "assets/stadiums/los-angeles.jpg",
      label: { dx: -245, dy: 36, anchor: "end" }
    },
    {
      id: "guadalajara",
      name: "Estadio Akron",
      city: "Guadalajara",
      country: "Mexico",
      countryFlag: "🇲🇽",
      region: "Mexico",
      capacity: 48000,
      lat: 20.6819,
      lng: -103.4622,
      status: "upcoming",
      image: "assets/stadiums/guadalajara.jpg",
      label: { dx: 28, dy: -34, anchor: "start" }
    },
    {
      id: "mexico-city",
      name: "Estadio Azteca",
      city: "Mexico City",
      country: "Mexico",
      countryFlag: "🇲🇽",
      region: "Mexico",
      capacity: 83000,
      lat: 19.3029,
      lng: -99.1505,
      status: "knockout",
      image: "assets/stadiums/mexico-city.jpg",
      label: { dx: 34, dy: 26, anchor: "start" }
    },
    {
      id: "monterrey",
      name: "Estadio BBVA",
      city: "Monterrey",
      country: "Mexico",
      countryFlag: "🇲🇽",
      region: "Mexico",
      capacity: 53500,
      lat: 25.6685,
      lng: -100.2445,
      status: "upcoming",
      image: "assets/stadiums/monterrey.jpg",
      label: { dx: 38, dy: -14, anchor: "start" }
    },
    {
      id: "dallas",
      name: "AT&T Stadium",
      city: "Dallas",
      country: "United States",
      countryFlag: "🇺🇸",
      region: "Central",
      capacity: 94000,
      lat: 32.7473,
      lng: -97.0945,
      status: "final",
      image: "assets/stadiums/dallas.jpg",
      label: { dx: -246, dy: 18, anchor: "end" }
    },
    {
      id: "houston",
      name: "NRG Stadium",
      city: "Houston",
      country: "United States",
      countryFlag: "🇺🇸",
      region: "Central",
      capacity: 72000,
      lat: 29.6847,
      lng: -95.4107,
      status: "upcoming",
      image: "assets/stadiums/houston.jpg",
      label: { dx: 36, dy: 12, anchor: "start" }
    },
    {
      id: "kansas-city",
      name: "Arrowhead Stadium",
      city: "Kansas City",
      country: "United States",
      countryFlag: "🇺🇸",
      region: "Central",
      capacity: 73000,
      lat: 39.0489,
      lng: -94.4839,
      status: "finished",
      image: "assets/stadiums/kansas-city.jpg",
      label: { dx: -260, dy: -18, anchor: "end" }
    },
    {
      id: "atlanta",
      name: "Mercedes-Benz Stadium",
      city: "Atlanta",
      country: "United States",
      countryFlag: "🇺🇸",
      region: "East Coast",
      capacity: 75000,
      lat: 33.7554,
      lng: -84.4009,
      status: "upcoming",
      image: "assets/stadiums/atlanta.jpg",
      label: { dx: 38, dy: -16, anchor: "start" }
    },
    {
      id: "miami",
      name: "Hard Rock Stadium",
      city: "Miami",
      country: "United States",
      countryFlag: "🇺🇸",
      region: "East Coast",
      capacity: 65000,
      lat: 25.9580,
      lng: -80.2389,
      status: "upcoming",
      image: "assets/stadiums/miami.jpg",
      label: { dx: 34, dy: -6, anchor: "start" }
    },
    {
      id: "toronto",
      name: "BMO Field",
      city: "Toronto",
      country: "Canada",
      countryFlag: "🇨🇦",
      region: "East Coast",
      capacity: 45000,
      lat: 43.6332,
      lng: -79.4186,
      status: "live",
      image: "assets/stadiums/toronto.jpg",
      label: { dx: -252, dy: -34, anchor: "end" }
    },
    {
      id: "boston",
      name: "Gillette Stadium",
      city: "Boston",
      country: "United States",
      countryFlag: "🇺🇸",
      region: "East Coast",
      capacity: 65000,
      lat: 42.0909,
      lng: -71.2643,
      status: "upcoming",
      image: "assets/stadiums/boston.jpg",
      label: { dx: 38, dy: -28, anchor: "start" }
    },
    {
      id: "new-york-new-jersey",
      name: "MetLife Stadium",
      city: "New York / New Jersey",
      country: "United States",
      countryFlag: "🇺🇸",
      region: "East Coast",
      capacity: 82500,
      lat: 40.8135,
      lng: -74.0745,
      status: "knockout",
      image: "assets/stadiums/new-york-new-jersey.jpg",
      label: { dx: 36, dy: 0, anchor: "start" }
    },
    {
      id: "philadelphia",
      name: "Lincoln Financial Field",
      city: "Philadelphia",
      country: "United States",
      countryFlag: "🇺🇸",
      region: "East Coast",
      capacity: 69000,
      lat: 39.9008,
      lng: -75.1675,
      status: "upcoming",
      image: "assets/stadiums/philadelphia.jpg",
      label: { dx: 36, dy: 38, anchor: "start" }
    }
  ],

  matches: [
    { id: "m01", stadiumId: "mexico-city", date: "2026-06-11T20:00:00-06:00", round: "Opening", status: "upcoming", teamA: "MEX", teamB: "POR", weather: "23°C · Clear" },
    { id: "m02", stadiumId: "los-angeles", date: "2026-06-12T18:00:00-07:00", round: "Group Stage", status: "live", teamA: "USA", teamB: "JPN", weather: "21°C · Mild" },
    { id: "m03", stadiumId: "toronto", date: "2026-06-12T20:00:00-04:00", round: "Group Stage", status: "live", teamA: "CAN", teamB: "MAR", weather: "18°C · Cloudy" },
    { id: "m04", stadiumId: "vancouver", date: "2026-06-13T16:00:00-07:00", round: "Group Stage", status: "upcoming", teamA: "ARG", teamB: "KOR", weather: "17°C · Clear" },
    { id: "m05", stadiumId: "seattle", date: "2026-06-14T17:00:00-07:00", round: "Group Stage", status: "upcoming", teamA: "BRA", teamB: "SEN", weather: "16°C · Light rain" },
    { id: "m06", stadiumId: "san-francisco", date: "2026-06-15T19:00:00-07:00", round: "Group Stage", status: "upcoming", teamA: "ESP", teamB: "AUS", weather: "18°C · Clear" },
    { id: "m07", stadiumId: "guadalajara", date: "2026-06-16T20:00:00-06:00", round: "Group Stage", status: "upcoming", teamA: "GER", teamB: "COL", weather: "26°C · Warm" },
    { id: "m08", stadiumId: "monterrey", date: "2026-06-17T21:00:00-06:00", round: "Group Stage", status: "upcoming", teamA: "FRA", teamB: "URU", weather: "29°C · Clear" },
    { id: "m09", stadiumId: "dallas", date: "2026-06-18T18:00:00-05:00", round: "Group Stage", status: "upcoming", teamA: "ENG", teamB: "GHA", weather: "30°C · Hot" },
    { id: "m10", stadiumId: "houston", date: "2026-06-19T20:00:00-05:00", round: "Group Stage", status: "upcoming", teamA: "NED", teamB: "QAT", weather: "31°C · Humid" },
    { id: "m11", stadiumId: "kansas-city", date: "2026-06-20T18:00:00-05:00", round: "Group Stage", status: "finished", teamA: "ITA", teamB: "SUI", score: "2–1", weather: "27°C · Clear" },
    { id: "m12", stadiumId: "atlanta", date: "2026-06-21T19:00:00-04:00", round: "Group Stage", status: "upcoming", teamA: "BEL", teamB: "CRO", weather: "28°C · Indoor" },
    { id: "m13", stadiumId: "miami", date: "2026-06-22T20:00:00-04:00", round: "Group Stage", status: "upcoming", teamA: "ARG", teamB: "MAR", weather: "29°C · Humid" },
    { id: "m14", stadiumId: "boston", date: "2026-06-23T18:00:00-04:00", round: "Group Stage", status: "upcoming", teamA: "BRA", teamB: "JPN", weather: "20°C · Clear" },
    { id: "m15", stadiumId: "new-york-new-jersey", date: "2026-07-05T19:00:00-04:00", round: "Round of 16", status: "knockout", teamA: "FRA", teamB: "SEN", weather: "25°C · Clear" },
    { id: "m16", stadiumId: "philadelphia", date: "2026-07-06T18:00:00-04:00", round: "Round of 16", status: "knockout", teamA: "ESP", teamB: "USA", weather: "27°C · Clear" },
    { id: "m17", stadiumId: "dallas", date: "2026-07-14T19:00:00-05:00", round: "Semi Final", status: "knockout", teamA: "ARG", teamB: "FRA", weather: "Indoor" },
    { id: "m18", stadiumId: "new-york-new-jersey", date: "2026-07-19T15:00:00-04:00", round: "Final", status: "final", teamA: "BRA", teamB: "ENG", weather: "26°C · Clear" }
  ],

  routes: [
    ["vancouver", "seattle", "san-francisco", "los-angeles"],
    ["guadalajara", "mexico-city", "monterrey", "dallas", "houston"],
    ["toronto", "boston", "new-york-new-jersey", "philadelphia", "atlanta", "miami"]
  ]
};
